site_name: BOFA Inc

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

theme:
  name: material
  palette:
    primary: lime
    scheme: slate
    accent: indigo
  logo: assets/logo.png
  favicon: assets/logo.png
